import { NextResponse } from "next/server";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth";
import { query } from "@/lib/db";
const schema = z.object({ id: z.coerce.number().int().positive().optional(), name: z.string().trim().min(2).max(120), category: z.string().trim().max(120).optional().nullable(), description: z.string().trim().max(1000).optional().nullable() });
export async function GET() { await requireAdmin(); const result = await query("SELECT id::integer AS id,name,category,description FROM skills ORDER BY name"); return NextResponse.json({ skills: result.rows }); }
export async function POST(request: Request) { await requireAdmin(); const parsed = schema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message }, { status: 400 }); try { const result = await query("INSERT INTO skills(name,category,description) VALUES($1,$2,$3) RETURNING id,name,category,description", [parsed.data.name, parsed.data.category || null, parsed.data.description || null]); return NextResponse.json(result.rows[0], { status: 201 }); } catch { return NextResponse.json({ error: "A skill with that name already exists." }, { status: 409 }); } }
export async function PUT(request: Request) { await requireAdmin(); const parsed = schema.safeParse(await request.json()); if (!parsed.success || !parsed.data.id) return NextResponse.json({ error: "Invalid skill." }, { status: 400 }); try { const result = await query("UPDATE skills SET name=$1,category=$2,description=$3 WHERE id=$4 RETURNING id,name,category,description", [parsed.data.name, parsed.data.category || null, parsed.data.description || null, parsed.data.id]); return result.rowCount ? NextResponse.json(result.rows[0]) : NextResponse.json({ error: "Skill not found." }, { status: 404 }); } catch { return NextResponse.json({ error: "A skill with that name already exists." }, { status: 409 }); } }
export async function DELETE(request: Request) { await requireAdmin(); const id = Number(new URL(request.url).searchParams.get("id")); if (!Number.isSafeInteger(id) || id < 1) return NextResponse.json({ error: "Invalid skill." }, { status: 400 }); const usage = await query("SELECT EXISTS(SELECT 1 FROM student_skills WHERE skill_id=$1) OR EXISTS(SELECT 1 FROM job_role_skills WHERE skill_id=$1) AS used", [id]); if (usage.rows[0]?.used) return NextResponse.json({ error: "This skill is in use and cannot be deleted." }, { status: 409 }); await query("DELETE FROM skills WHERE id=$1", [id]); return NextResponse.json({ ok: true }); }
