"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";
import { CURRENT_YEARS } from "@/lib/constants";
type Option = { id:number; name:string }; const initial={fullName:"",email:"",password:"",confirmPassword:"",contactNumber:"",collegeId:"",branchId:"",currentYear:"",careerGoal:""};
export function AuthForm({mode}:{mode:"login"|"register"}) { const router=useRouter(), register=mode==="register"; const [data,setData]=useState(initial),[colleges,setColleges]=useState<Option[]>([]),[branches,setBranches]=useState<Option[]>([]),[search,setSearch]=useState(""),[state,setState]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false);
useEffect(()=>{if(register) fetch(`/api/colleges?search=${encodeURIComponent(search)}&state=${encodeURIComponent(state)}`).then(async r=>{const x=await r.json();if(!r.ok)throw Error(x.error);setColleges(x.colleges)}).catch(e=>setError(e instanceof Error?e.message:"Unable to load colleges."))},[register,search,state]);
useEffect(()=>{if(!data.collegeId){setBranches([]);return} fetch(`/api/colleges/${data.collegeId}/branches`).then(async r=>{const x=await r.json();if(!r.ok)throw Error(x.error);setBranches(x.branches)}).catch(e=>setError(e instanceof Error?e.message:"Unable to load branches."))},[data.collegeId]);
const update=(name:string,value:string)=>setData(x=>({...x,[name]:value})); async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");setLoading(true);try{const r=await fetch(`/api/auth/${mode}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const x=await r.json();if(!r.ok)throw Error(x.error||"Something went wrong.");router.push("/dashboard");router.refresh()}catch(e){setError(e instanceof Error?e.message:"Something went wrong.")}finally{setLoading(false)}}
return <form onSubmit={submit} className="space-y-4" noValidate>{register&&<><Field label="Full Name" name="fullName" value={data.fullName} onChange={update}/><Field label="Contact Number" name="contactNumber" value={data.contactNumber} onChange={update} type="tel"/><div className="grid gap-3 sm:grid-cols-2"><Field label="State (optional)" name="state" value={state} onChange={(_,v)=>setState(v)}/><Field label="Search College" name="search" value={search} onChange={(_,v)=>setSearch(v)}/></div><Select label="College / Institute" name="collegeId" value={data.collegeId} options={colleges} placeholder="Select your college" onChange={(n,v)=>{update(n,v);update("branchId","")}}/><Select label="Branch" name="branchId" value={data.branchId} options={branches} placeholder={data.collegeId?"Select your branch":"Select a college first"} onChange={update}/><Select label="Current Year" name="currentYear" value={data.currentYear} options={CURRENT_YEARS.map((name,id)=>({id,name}))} placeholder="Select current year" onChange={update} textValue/></>}<Field label="Email" name="email" value={data.email} onChange={update} type="email"/><Field label="Password" name="password" value={data.password} onChange={update} type="password"/>{register&&<><Field label="Confirm Password" name="confirmPassword" value={data.confirmPassword} onChange={update} type="password"/><label className="block"><span className="label">Career Goal / Future Job Vision</span><textarea required className="field min-h-28" value={data.careerGoal} onChange={e=>update("careerGoal",e.target.value)}/></label></>}{error&&<p role="alert" className="status-error p-3">{error}</p>}<button className="btn-primary w-full" disabled={loading||(register&&(!data.collegeId||!data.branchId))}>{loading?"Please wait…":register?"Create account":"Login"}</button><p className="text-center text-sm text-slate-600">{register?<>Already have an account? <Link className="font-semibold text-brand" href="/login">Login</Link></>:<>New to JOB-LEARNER? <Link className="font-semibold text-brand" href="/register">Create an account</Link></>}</p></form> }
function Field({label,name,value,onChange,type="text"}:{label:string;name:string;value:string;onChange:(n:string,v:string)=>void;type?:string}){return <label className="block"><span className="label">{label}</span><input className="field" required={name!=="state"&&name!=="search"} type={type} value={value} onChange={e=>onChange(name,e.target.value)}/></label>}; function Select({label,name,value,options,placeholder,onChange,textValue}:{label:string;name:string;value:string;options:Option[];placeholder:string;onChange:(n:string,v:string)=>void;textValue?:boolean}){return <label className="block"><span className="label">{label}</span><select required className="field" value={value} onChange={e=>onChange(name,e.target.value)}><option value="">{placeholder}</option>{options.map(o=><option key={o.id} value={textValue?o.name:o.id}>{o.name}</option>)}</select></label>}
