import Link from "next/link";
import { currentUserId } from "@/lib/auth";
import { ThemeToggle } from "@/components/theme-toggle";
import { BrandLogo } from "@/components/brand-logo";

export async function Navbar() {
  const signedIn = Boolean(await currentUserId()); const logoHref = signedIn ? "/dashboard" : "/"; const home = logoHref; const dashboardHref = signedIn ? "/dashboard" : "/login"; const gated = (path:string) => signedIn ? path : "/login";
  return <header className="sticky top-0 z-30 border-b border-stone-200 bg-cream/95 backdrop-blur"><nav className="container-page flex items-center justify-between gap-3 py-3"><BrandLogo href={logoHref} showTagline={false} className="public-brand"/><div className="hidden items-center gap-4 text-sm font-semibold text-stone-600 xl:flex"><Link href={home}>Home</Link><Link href="/#features">Features</Link><Link href="/#how-it-works">How it works</Link><Link href={gated("/skill-gap")}>Skill Gap</Link><Link href={gated("/verified-skills")}>Verified Profile</Link><Link href={gated("/career-insights")}>Insights</Link><Link href={gated("/roadmap")}>Roadmap</Link><Link href="/#about">About</Link></div><div className="flex shrink-0 items-center gap-2"><ThemeToggle responsiveCompact/><details className="relative lg:hidden"><summary className="cursor-pointer list-none rounded-xl border border-stone-300 px-3 py-2 text-sm font-semibold text-stone-700">Menu</summary><div className="absolute right-0 mt-2 w-52 rounded-xl border border-stone-200 bg-white p-2 shadow-card"><Link className="block rounded-lg px-3 py-2 hover:bg-rose-50" href={home}>Home</Link><Link className="block rounded-lg px-3 py-2 hover:bg-rose-50" href="/#features">Features</Link><Link className="block rounded-lg px-3 py-2 hover:bg-rose-50" href="/#how-it-works">How it works</Link><Link className="block rounded-lg px-3 py-2 hover:bg-rose-50" href={gated("/skill-gap")}>Skill Gap</Link><Link className="block rounded-lg px-3 py-2 hover:bg-rose-50" href={gated("/verified-skills")}>Verified Profile</Link><Link className="block rounded-lg px-3 py-2 hover:bg-rose-50" href={gated("/career-insights")}>Career Insights</Link><Link className="block rounded-lg px-3 py-2 hover:bg-rose-50" href={gated("/roadmap")}>Roadmap</Link><Link className="block rounded-lg px-3 py-2 hover:bg-rose-50" href={dashboardHref}>Dashboard</Link></div></details><div className="hidden items-center gap-2 lg:flex">{!signedIn && <Link className="px-3 py-2 text-sm font-semibold text-stone-700" href="/login">Login</Link>}<Link className="btn-primary px-4 py-2 text-sm" href={dashboardHref}>Dashboard</Link></div></div></nav></header>;
}
