"use client";

import { useEffect, useMemo, useState } from "react";

type Note = { id:string; title:string; content:string; subject:string; tags:string; updatedAt:string };
const blank = (): Note => ({ id: crypto.randomUUID(), title:"Untitled note", content:"", subject:"", tags:"", updatedAt:new Date().toISOString() });

export function NotesNotebook({ storageKey }: { storageKey:string }) {
  const [notes, setNotes] = useState<Note[]>([]); const [selectedId, setSelectedId] = useState<string | null>(null); const [search, setSearch] = useState(""); const [ready, setReady] = useState(false);
  useEffect(() => { try { const saved = localStorage.getItem(storageKey); if (saved) { const parsed = JSON.parse(saved) as Note[]; setNotes(parsed); setSelectedId(parsed[0]?.id ?? null); } } catch { /* Browser storage is optional. */ } setReady(true); }, [storageKey]);
  useEffect(() => { if (ready) localStorage.setItem(storageKey, JSON.stringify(notes)); }, [notes, ready, storageKey]);
  const selected = notes.find(note => note.id === selectedId) ?? null;
  const visible = useMemo(() => notes.filter(note => `${note.title} ${note.subject} ${note.tags} ${note.content}`.toLowerCase().includes(search.toLowerCase())), [notes, search]);
  const create = () => { const note = blank(); setNotes(current => [note, ...current]); setSelectedId(note.id); };
  const update = (changes: Partial<Note>) => selected && setNotes(current => current.map(note => note.id === selected.id ? { ...note, ...changes, updatedAt:new Date().toISOString() } : note));
  const remove = () => { if (!selected || !window.confirm(`Delete “${selected.title || "this note"}”?`)) return; setNotes(current => current.filter(note => note.id !== selected.id)); setSelectedId(notes.find(note => note.id !== selected.id)?.id ?? null); };
  return <div className="mt-8 grid min-h-[620px] overflow-hidden rounded-2xl border bg-[color:var(--jl-surface)] shadow-[var(--jl-shadow)] lg:grid-cols-[280px_minmax(0,1fr)]">
    <aside className="border-b p-4 lg:border-b-0 lg:border-r"><button onClick={create} className="btn-primary w-full">＋ Create note</button><label className="sr-only" htmlFor="note-search">Search notes</label><input id="note-search" className="field" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search notes"/><div className="mt-4 max-h-[460px] space-y-2 overflow-y-auto">{visible.map(note => <button key={note.id} onClick={() => setSelectedId(note.id)} className={`w-full rounded-xl border p-3 text-left transition ${note.id===selectedId ? "border-[color:var(--jl-primary)] bg-[color:var(--jl-surface-muted)]" : "hover:bg-[color:var(--jl-canvas-soft)]"}`}><p className="truncate text-sm font-bold">{note.title || "Untitled note"}</p><p className="mt-1 truncate text-xs text-stone-500">{note.subject || "General"}{note.tags ? ` · ${note.tags}` : ""}</p></button>)}{ready&&!visible.length&&<p className="px-2 py-6 text-center text-sm text-stone-500">{notes.length ? "No matching notes." : "Create your first study note."}</p>}</div></aside>
    <section className="min-w-0 p-4 sm:p-6">{selected ? <div className="mx-auto max-w-3xl"><div className="flex flex-wrap items-center justify-between gap-3"><p className="eyebrow">Study note</p><button onClick={remove} className="rounded-lg px-3 py-2 text-sm font-bold text-[color:var(--jl-danger)] hover:bg-[color:var(--jl-danger-soft)]">Delete note</button></div><input aria-label="Note title" className="mt-4 w-full border-0 bg-transparent text-2xl font-bold outline-none placeholder:text-stone-400 sm:text-3xl" value={selected.title} onChange={event => update({title:event.target.value})} placeholder="Note title"/><div className="mt-5 grid gap-3 sm:grid-cols-2"><input aria-label="Subject or topic" className="field mt-0" value={selected.subject} onChange={event => update({subject:event.target.value})} placeholder="Subject or topic"/><input aria-label="Tags" className="field mt-0" value={selected.tags} onChange={event => update({tags:event.target.value})} placeholder="Tags (comma separated)"/></div><label className="label mt-5 block" htmlFor="note-content">Content</label><textarea id="note-content" className="field min-h-[320px] resize-y leading-7" value={selected.content} onChange={event => update({content:event.target.value})} placeholder="Write your notes here…"/><p className="mt-3 text-xs text-stone-500">Stored privately in this browser for this JOB-LEARNER account. Database sync can be added later.</p></div> : <div className="status-empty mx-auto mt-20 max-w-md"><b className="block text-[color:var(--jl-text)]">Your study notebook is ready</b><p className="mt-2 text-sm">Create a note for a subject, topic, revision plan, or idea.</p><button onClick={create} className="btn-primary mt-5">Create note</button></div>}</section>
  </div>;
}
