"use client";
import { useEffect, useState } from "react";
import { formatDateShort } from "@/lib/date";
type Skill = { id: number; name: string; category?: string }; type StudentSkill = { skillId: number; skillName: string; category?: string; proficiencyLevel: number }; type SkillNote = { id: number; note: string; createdAt: string };
const stages = ["Beginner", "Basic", "Intermediate", "Advanced", "Mastered"] as const;
function stageFor(level: number) { return stages[level - 1] ?? stages[0]; }
function SkillProficiencyStars({ value, onChange }: { value: number; onChange: (value: number) => void }) { const [hovered, setHovered] = useState<number | null>(null); const highlighted = hovered ?? value; return <div className="skill-proficiency" onMouseLeave={() => setHovered(null)}><div className="skill-stars" role="radiogroup" aria-label="Skill proficiency">{[1,2,3,4,5].map(star => <button key={star} type="button" role="radio" aria-checked={value === star} aria-label={`Set proficiency to ${star} star${star === 1 ? "" : "s"} — ${stageFor(star)}`} onMouseEnter={() => setHovered(star)} onFocus={() => setHovered(star)} onBlur={() => setHovered(null)} onClick={() => onChange(star)} className={`skill-star ${star <= highlighted ? "skill-star-selected" : ""}`}>★</button>)}</div><span className="skill-stage" aria-live="polite">{stageFor(value)}</span></div>; }
async function readSkillNotesResponse(response: Response) {
  const body = await response.text();
  if (!body) return { data: null, error: "The server returned an empty response." };
  try { return { data: JSON.parse(body) as { error?: string; notes?: SkillNote[]; note?: SkillNote }, error: "" }; }
  catch { return { data: null, error: "The server returned an invalid response." }; }
}
function SkillNotes({ skillId }: { skillId: number }) { const [expanded,setExpanded]=useState(false),[notes,setNotes]=useState<SkillNote[]>([]),[draft,setDraft]=useState(""),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(""); async function load(){setLoading(true);setError("");try{const r=await fetch(`/api/student/skills/${skillId}/notes`),parsed=await readSkillNotesResponse(r);if(!r.ok||!parsed.data)throw Error(parsed.data?.error||parsed.error||"Unable to load notes.");setNotes(parsed.data.notes||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load notes.")}finally{setLoading(false)}}async function toggle(){const next=!expanded;setExpanded(next);if(next&&!notes.length)await load()}async function save(){if(!draft.trim())return setError("Write a progress note before saving.");setSaving(true);setError("");try{const r=await fetch(`/api/student/skills/${skillId}/notes`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({note:draft})}),parsed=await readSkillNotesResponse(r);if(!r.ok||!parsed.data?.note)throw Error(parsed.data?.error||parsed.error||"Unable to save note.");setNotes(current=>[parsed.data!.note!,...current]);setDraft("")}catch(e){setError(e instanceof Error?e.message:"Unable to save note.")}finally{setSaving(false)}}return <section className="skill-notes"><button type="button" className="skill-notes-toggle" aria-expanded={expanded} aria-controls={`skill-notes-${skillId}`} onClick={toggle}><span aria-hidden>{expanded?"⌄":"›"}</span> Skill notes</button>{expanded&&<div id={`skill-notes-${skillId}`} className="skill-notes-content"><label className="sr-only" htmlFor={`skill-note-${skillId}`}>Progress note for this skill</label><textarea id={`skill-note-${skillId}`} className="field min-h-28 resize-y" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Record what you learned, practiced, or improved..." maxLength={3000}/><div className="mt-3 flex flex-wrap items-center gap-3"><button type="button" className="btn-primary px-4 py-2 text-sm" onClick={save} disabled={saving}>{saving?"Saving…":"Save note"}</button>{error&&<p className="text-sm text-[color:var(--jl-danger)]" role="alert">{error}</p>}</div><div className="mt-5"><h4 className="text-sm font-bold">Progress history</h4>{loading?<p className="mt-2 text-sm text-stone-500">Loading notes…</p>:notes.length?<ol className="skill-note-history">{notes.map(note=><li key={note.id}><time dateTime={note.createdAt}>{formatDateShort(note.createdAt)}</time><p>{note.note}</p></li>)}</ol>:<p className="mt-2 text-sm text-stone-500">No progress notes yet.</p>}</div></div>}</section>; }
export function StudentSkillsManager() { const [all,setAll]=useState<Skill[]>([]),[items,setItems]=useState<StudentSkill[]>([]),[skillId,setSkillId]=useState(""),[level,setLevel]=useState(1),[error,setError]=useState("");const load=()=>fetch("/api/student/skills").then(r=>r.json()).then(x=>setItems(x.skills||[]));useEffect(()=>{fetch("/api/skills").then(r=>r.json()).then(x=>setAll(x.skills||[]));load()},[]);async function add(e:React.FormEvent){e.preventDefault();setError("");const r=await fetch("/api/student/skills",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({skillId,proficiencyLevel:level})}),x=await r.json();if(!r.ok)return setError(x.error||"Unable to add skill.");setSkillId("");setLevel(1);load()}async function change(id:number,proficiencyLevel:number){const r=await fetch(`/api/student/skills/${id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({proficiencyLevel})});if(!r.ok)setError((await r.json()).error||"Unable to update skill.");else load()}async function remove(id:number){const r=await fetch(`/api/student/skills/${id}`,{method:"DELETE"});if(!r.ok)setError((await r.json()).error||"Unable to remove skill.");else load()}const available=all.filter(skill=>!items.some(item=>item.skillId===skill.id));return <section className="surface mt-8 p-6"><h2 className="text-xl font-bold text-ink">My Skills</h2><p className="mt-1 text-sm text-slate-500">Add skills and choose the learning stage that reflects your current proficiency.</p><form className="mt-5 flex flex-col gap-4 rounded-xl border p-4 sm:flex-row sm:flex-wrap sm:items-end" onSubmit={add}><label className="min-w-0 flex-1"><span className="label">Skill</span><select required className="field" value={skillId} onChange={e=>setSkillId(e.target.value)}><option value="">Select a skill</option>{available.map(skill=><option key={skill.id} value={skill.id}>{skill.name}</option>)}</select></label><div><span className="label block">Starting proficiency</span><SkillProficiencyStars value={level} onChange={setLevel}/></div><button className="btn-primary sm:mb-0.5">Add skill</button></form>{error&&<p className="mt-3 text-sm text-red-600" role="alert">{error}</p>}<div className="mt-5 space-y-3">{items.map(item=><article className="skill-entry" key={item.skillId}><div className="skill-entry-main"><div className="min-w-0"><h3 className="font-bold">{item.skillName}</h3>{item.category&&<p className="mt-1 text-sm text-stone-500">{item.category}</p>}</div><SkillProficiencyStars value={item.proficiencyLevel} onChange={value=>change(item.skillId,value)}/><button type="button" className="skill-remove" onClick={()=>remove(item.skillId)}>Remove</button></div><SkillNotes skillId={item.skillId}/></article>)}{!items.length&&<p className="py-4 text-sm text-slate-500">No skills added yet.</p>}</div></section>; }
