import { NextResponse } from "next/server";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth";
import { query, withTransaction } from "@/lib/db";
const roleSchema = z.object({ id: z.coerce.number().int().positive().optional(), title: z.string().trim().min(2).max(160), description: z.string().trim().max(1000).optional().nullable(), category: z.string().trim().max(120).optional().nullable() });
const mappingsSchema = z.object({ jobRoleId: z.coerce.number().int().positive(), skills: z.array(z.object({ skillId: z.coerce.number().int().positive(), requiredLevel: z.coerce.number().int().min(1).max(5), importance: z.coerce.number().int().min(1).max(5) })).max(100) });
export async function GET(request: Request) { await requireAdmin(); const roleId = Number(new URL(request.url).searchParams.get("roleId")); if (Number.isSafeInteger(roleId) && roleId > 0) { const result = await query("SELECT jrs.skill_id::integer AS \"skillId\",s.name AS \"skillName\",jrs.required_level AS \"requiredLevel\",jrs.importance FROM job_role_skills jrs JOIN skills s ON s.id=jrs.skill_id WHERE jrs.job_role_id=$1 ORDER BY s.name", [roleId]); return NextResponse.json({ skills: result.rows }); } const result = await query("SELECT id::integer AS id,title,description,category FROM job_roles ORDER BY title"); return NextResponse.json({ jobRoles: result.rows }); }
export async function POST(request: Request) { await requireAdmin(); const parsed = roleSchema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message }, { status: 400 }); try { const result = await query("INSERT INTO job_roles(title,description,category) VALUES($1,$2,$3) RETURNING id,title,description,category", [parsed.data.title, parsed.data.description || null, parsed.data.category || null]); return NextResponse.json(result.rows[0], { status: 201 }); } catch { return NextResponse.json({ error: "A job role with that title already exists." }, { status: 409 }); } }
export async function PUT(request: Request) { await requireAdmin(); const body = await request.json(); if (body.skills !== undefined) { const parsed = mappingsSchema.safeParse(body); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message ?? "Invalid skill mappings." }, { status: 400 }); const unique = new Set(parsed.data.skills.map((skill) => skill.skillId)); if (unique.size !== parsed.data.skills.length) return NextResponse.json({ error: "A skill can only be mapped once." }, { status: 400 }); const result = await withTransaction(async (client) => { const role = await client.query("SELECT 1 FROM job_roles WHERE id=$1", [parsed.data.jobRoleId]); if (!role.rowCount) throw new Error("Job role not found."); if (unique.size) { const skills = await client.query("SELECT id FROM skills WHERE id=ANY($1::bigint[])", [[...unique]]); if (skills.rowCount !== unique.size) throw new Error("One or more skills do not exist."); } await client.query("DELETE FROM job_role_skills WHERE job_role_id=$1", [parsed.data.jobRoleId]); for (const skill of parsed.data.skills) await client.query("INSERT INTO job_role_skills(job_role_id,skill_id,required_level,importance) VALUES($1,$2,$3,$4)", [parsed.data.jobRoleId, skill.skillId, skill.requiredLevel, skill.importance]); return true; }); return NextResponse.json({ ok: result }); }
  const parsed = roleSchema.safeParse(body); if (!parsed.success || !parsed.data.id) return NextResponse.json({ error: "Invalid job role." }, { status: 400 }); try { const result = await query("UPDATE job_roles SET title=$1,description=$2,category=$3 WHERE id=$4 RETURNING id,title,description,category", [parsed.data.title, parsed.data.description || null, parsed.data.category || null, parsed.data.id]); return result.rowCount ? NextResponse.json(result.rows[0]) : NextResponse.json({ error: "Job role not found." }, { status: 404 }); } catch { return NextResponse.json({ error: "A job role with that title already exists." }, { status: 409 }); } }
export async function DELETE(request: Request) { await requireAdmin(); const id = Number(new URL(request.url).searchParams.get("id")); if (!Number.isSafeInteger(id) || id < 1) return NextResponse.json({ error: "Invalid job role." }, { status: 400 }); try { await query("DELETE FROM job_roles WHERE id=$1", [id]); return NextResponse.json({ ok: true }); } catch { return NextResponse.json({ error: "This job role is selected by students and cannot be deleted." }, { status: 409 }); } }
